variables:
- group: ServiceConnections
- name: azureSubscription
  value: $(ServiceConnectionPRD1)
- name: docker.imageName
  value: 'documentschemajobrunner'
- name: acr.azureContainerRegistryName
  value: 'prdrwdinfac1401'
- name: acr.repositoryName
  value: 'documentschemajobrunnerrepository'
- name: serviceName
  value: 'prdrwdwebfa1406'
