variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'documentschemajobrunner'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'documentschemajobrunnerrepository'
  serviceName: 'prdrwdwebfa1406'
